# Generated by Django 5.0.6 on 2024-08-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="full_name",
            field=models.CharField(
                default="ok", help_text="Enter your full name", max_length=70
            ),
        ),
    ]
