# Generated by Django 5.0.6 on 2024-08-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(default="profilepic.png", upload_to="profilepics"),
        ),
    ]
