# Generated by Django 5.0.6 on 2024-08-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="profilepics/profilepic.png", upload_to="profilepics"
            ),
        ),
    ]
