# Generated by Django 5.0.6 on 2024-08-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="full_name",
            field=models.CharField(help_text="Enter your full name", max_length=70),
        ),
    ]
