# Generated by Django 5.0.6 on 2024-06-29 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='item',
            table='Item',
        ),
    ]
