# Generated by Django 5.0.6 on 2024-07-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://images.unsplash.com/photo-1572373549709-c78b9d41b864', max_length=500),
        ),
    ]
