# Generated by Django 5.0.6 on 2024-07-21 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0006_alter_item_item_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_image",
            field=models.ImageField(blank=True, upload_to="food_images"),
        ),
    ]
