# Generated by Django 5.0.6 on 2024-08-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0007_alter_item_item_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_image",
            field=models.ImageField(upload_to="food_images"),
        ),
    ]
