# Generated by Django 5.0.6 on 2024-08-04 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0008_alter_item_item_image"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="item",
            table=None,
        ),
    ]
